### ISSUE TITLE
Arguments not following standard integration

### ISSUE THREAD

**Issue by jeremenichelli** [iamdustan/smoothscroll#10]
I've noticed that **Firefox** is the only browser which has this behavior enable by default. The thing is that inside the ```window.scroll``` declaration it expects an object while it still gives supports for the old two number arguments. 
```js
window.scroll({
    top: 120,
    left: 20,
   behavior: 'smooth'
});
```
Since **Firefox** is expecting this, the script will return because it finds that ```smoothBehavior```is implemented and never work.

If you are ok with this, I can create a pull request with all the necessary changes to adapt your script to this type of call which I guess is the standard one instead of the actual that doesn't have an options object.

**Comment by jiyinyiyong** [comment]
So what's next... I found Firefox odd too.
