### ISSUE TITLE
Kill bower.json file?

### ISSUE THREAD

**Issue by jeremenichelli** [iamdustan/smoothscroll#103]
We should start considering eliminating the `bower.json` file since it's already deprecated. This is a message that you get when installing it globally:

```sh
WARN deprecated bower@1.8.2: ...psst! Your project can stop working at any moment because its dependencies can change. Prevent this by migrating to Yarn: https://bower.io/blog/2017/how-to-migrate-away-from-bower/
```

What do you think? @iamdustan

**Comment by iamdustan** [comment]
yeaaah kill it!

**Comment by jeremenichelli** [comment]
I'm working on infrastructure changes for better releases and PRs, so I'm gonna include it there.

Sat tuned 📻
