### ISSUE TITLE
scrollIntoView fails on document.body

### ISSUE THREAD

**Issue by jeremenichelli** [iamdustan/smoothscroll#105]
I realized the scripts throws an error when calling `document.body.scrollIntoView({ behavior: 'smooth' })` after investigating https://github.com/iamdustan/smoothscroll/issues/28 issue.

We also need to investigate the expected behavior of that function call, since Chrome does nothing while Firefox scrolls to top.

**Comment by graygilmore** [comment]
Looks like Chrome, Firefox, Safari, and Edge all behave as expected when using `document.body` and go to the top of the page: https://s.codepen.io/graygilmore/debug/RJgYRx

Only Chrome and Firefox respect the `smooth` behaviour still, though.
