### ISSUE TITLE
Move to yarn?

### ISSUE THREAD

**Issue by jeremenichelli** [iamdustan/smoothscroll#107]
Would love to know your thoughts on this Dustan.

**Comment by iamdustan** [comment]
Dooooeeeetttt!

**Comment by jeremenichelli** [comment]
LOL, awesome! I will add it to this one https://github.com/iamdustan/smoothscroll/pull/104

You can review it without the yarn, I'll just update the docs and generate the lock file.

**Comment by Bessonov** [comment]
Just my personal view: after switch to npm 5 there is no need for yarn.

**Comment by Bessonov** [comment]
Regardless of npm 5 or yarn - play with the lock file. It's a nice idea, but well, it's very cumbersome to have it in git. I don't found best strategy to handle this file.

**Comment by jeremenichelli** [comment]
It's true that there aren't huge differences with npm5. I do like better how it handle scripts, flags and on screen messages.

Either way, people will only need it if they collaborate with code which doesn't happen often, and having to install yarn is not a curse or a big blocker.
