### ISSUE TITLE
This dependency was not found

### ISSUE THREAD

**Issue by steida** [iamdustan/smoothscroll#111]
Probably one of the last updates is broken. It worked a few days ago.

This dependency was not found:

* smoothscroll-polyfill in ./components/app/index.js

To install it, you can run: npm install --save smoothscroll-polyfill

**Comment by steida** [comment]
![screen shot 2018-02-25 at 20 37 07](https://user-images.githubusercontent.com/66249/36645603-ae63e778-1a6b-11e8-9a7d-e24e500ebe29.png)

**Comment by jeremenichelli** [comment]
Can you describe briefly your bundler config?

**Comment by jeremenichelli** [comment]
Temporarely you can remove the `^` and roll back to `0.4.0`, I'm looking into this to see as we speak.

**Comment by jeremenichelli** [comment]
This was already solved in a patch release @steida.

Run install script again and `0.4.3` should work just fine, thanks for reporting!

**Comment by steida** [comment]
Thank you. Btw, do you know what happens when IE, Safari, Edge or anything else will get behavior option without a polyfill? Will it crash? I removed smoothscroll-polyfill from my app hoping it will just not animate, nothing else. Am I correct? Thank you.

**Comment by jeremenichelli** [comment]
My best guess is that the window will scroll without being animated in modern browsers, but it could break in older ones if you don't include the polyfill.

If you are going to set the behavior like this:

```js
window.scroll({ top: 500, behavior: 'smooth' });
```

I would wrap it in a try catch statement or include the polyfill, or use the old not animated notation. I wouldn't trust browsers to "just work" when the Scroll Behavior spec is not implemented, it's a really long shot.

**Comment by iamdustan** [comment]
In 95% certain it will just work. These methods have supported object options for a looooong time so browsers will just ignore the unknown options

**Comment by jeremenichelli** [comment]
Yeah, not putting my foot down for old Internet Explorer that might not like unknown properties on the options object.
