### ISSUE TITLE
The behaviour of scrollIntoView is not identical with the Working Draft

### ISSUE THREAD

**Issue by huiyiqun** [iamdustan/smoothscroll#112]
As described [here](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView), if the option of `scrollIntoView` is an Object, it could have following properties:

* behavior
* block
* inline

However it seems that only the `behavior` is taken while `block` and `inline` are both ignored.

**Comment by jeremenichelli** [comment]
Hi @huiyiqun, we are aware that we are missing that part of the implementation. There's already an issue to express that: https://github.com/iamdustan/smoothscroll/issues/87
