### ISSUE TITLE
Keeping the hash in the URL

### ISSUE THREAD

**Issue by brandondurham** [iamdustan/smoothscroll#118]
Is it possible to keep the hash in the URL _and_ use smoothscroll?

So, too be clear, I’d like to be able to click a link with a hash, add the hash to the URL (as it does by default), then trigger smoothscroll. I can add the hash myself, but wanted to see if there was an inherent way to do this.

Thank you!

**Comment by jeremenichelli** [comment]
You can do it with JavaScript, capturing the hash in the href of the link and doing:

```js
document.getElementById('value_of_href').scrollIntoView({ behavior: 'smooth' });
```

The specs allows you to use the `scroll-behavior` property on body but this polyfill doesn't cover it.
