### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by ljharb** [iamdustan/smoothscroll#121]
There's no changelog, so I'm not clear on what breaking changes necessitated v0.4.0 from v0.3.6.

**Comment by robinwhittleton** [comment]
I agree that a changelog would be nice, but at a pinch Github’s compare functionality helps: https://github.com/iamdustan/smoothscroll/compare/v0.3.6...v0.4.2

**Comment by ljharb** [comment]
I already looked at that, but unfortunately that doesn't really help me get a clean summary of what changed.

**Comment by ljharb** [comment]
@iamdustan lol thanks, it's a good start, but this issue was specifically about describing the bump to v0.4.0 :-)

**Comment by iamdustan** [comment]
:joy: haha I definitely was not expecting this to be seen. Going forward with my one patch bump a year I think I’ll be able to manage maintaining a Changelog. Needless to say, I didn’t expect anyone would use this. Whoops.

**Comment by ljharb** [comment]
@iamdustan at the very least, can you perhaps summarize the breaking changes that led to v0.4?
