### ISSUE TITLE
Error scrolling into element inside Shadow DOM

### ISSUE THREAD

**Issue by inyigo** [iamdustan/smoothscroll#122]
Browser: Safari

Imported via https://unpkg.com/smoothscroll-polyfill@0.4.3/dist/smoothscroll.min.js

```
TypeError: null is not an object (evaluating 'o.clientHeight')
```

<img width="425" alt="screen shot 2018-06-21 at 9 40 08 pm" src="https://user-images.githubusercontent.com/405883/41722639-b521d4a4-759b-11e8-8936-2b4b6fc1938c.png">

Tried using this polyfill for an app implemented in polymer  2 which uses shadow DOM v1. I haven't investigated much because I have no clue where to start. If you can lead me into the right direction I might be able to help.

**Comment by Jbernardyoobic** [comment]
Browser: Safari

Same issue here : TypeError: null is not an object (evaluating 'el.clientHeight')
function findScrollableParent(el) {
      var isBody;

      do {
        el = el.parentNode;

        isBody = el === d.body;
      } while (isBody === false && isScrollable(el) === false);

      isBody = null;

      return el;
    }
The problem is el = el.parentNode which in case of a shadow DOM returns null
