### ISSUE TITLE
npm package has not been published

### ISSUE THREAD

**Issue by jeremenichelli** [iamdustan/smoothscroll#15]
Package is not in npm directory: https://www.npmjs.com/package/smoothscroll
Make sure you have the last version and run `npm publish`.

**Comment by DylanPiercey** [comment]
+1

**Comment by iamdustan** [comment]
Thanks for the reminder. On paternity leave at the moment but will publish this next time I'm on my computer.

**Comment by jeremenichelli** [comment]
Published https://www.npmjs.com/package/smoothscroll-polyfill
