### ISSUE TITLE
Smoothscroll Flickering Page Elements and too fast on Safari 13.0.5

### ISSUE THREAD

**Issue by geral-dscoimbra** [iamdustan/smoothscroll#152]
I have a website in overflow:hidden style, only letting you scroll the entire page.

On Safari 13.0.5 the nav-bar on the right is flickering and when i scroll multiple pages it goes way too fast.

![image](https://user-images.githubusercontent.com/55546753/78944395-b6a29900-7ab5-11ea-841d-6e771a8b4d72.png)

You can look at this behaviour at [test.dscoimbra.pt](url)

If you can't reproduce the behaviour, I'll upload a video of it.

Thank you for your help.

**Comment by geral-dscoimbra** [comment]
I am using React and Next.js and I'm importing the polyfill on __app.jsx and initialising it on componentDidMount()

```
import '../global.css';

import App from 'next/app';
import LoadingBlocker from '../components/loading-blocker/LoadingBlocker';
import { Provider } from 'react-redux';
import React from 'react';
import smoothscroll from 'smoothscroll-polyfill';
import store from '../redux/store/index';

class MyApp extends App {
  componentDidMount() {
    smoothscroll.polyfill();
  }

  render() {
    const { Component, pageProps } = this.props;
    return (
      <Provider store={store}>
        <LoadingBlocker />
        <Component {...pageProps} />
      </Provider>
    );
  }
}

export default MyApp;
```

**Comment by iamdustan** [comment]
Hey [deleted-account], I checked out your site briefly and can definitely see the bug. However this does not appear to be related to this polyfill.

I noticed that by disabling the `transform: translateY(-50%)` style that Safari no longer behaves broken. I would recommend finding a way to solve your UI intent without the transform.
