### ISSUE TITLE
smooth scroll is not working in chrome version>=81

### ISSUE THREAD

**Issue by Bettaswamy** [iamdustan/smoothscroll#154]
```
if (document.querySelector(target)) {
                    event.preventDefault();
                    document.querySelector(target).scrollIntoView({ behavior: 'smooth' });
                }`
```
```

if (document.querySelector(target)) {
                    event.preventDefault();
                    document.querySelector(target).scrollIntoView();
                }
```

Tried both the ways in chrome Version 81.0.4044.138(official-build). but no luck, smooth scroll is not working. But the same is working in IE and firefox. By setting inside a time out function also didnt do the trick. 

Also noticed one thing in other versions like 71.0 smooth scroll is working fine

**Comment by imkrmgn** [comment]
I had the same experience, but it worked when I enabled animations for Windows display settings.
This seems to be by design for the scroll-behavior CSS property.

**Comment by Bettaswamy** [comment]
@imkrmgn  thanks a lot mate after changing the display settings ,, booom,, started  working for me
