### ISSUE TITLE
[Feature Request] Padding option

### ISSUE THREAD

**Issue by davestewart** [iamdustan/smoothscroll#155]
It would be great if you could specify some padding for items when scrolled into view so they don't appear stuck to the edge of the viewport:

```
document
  .querySelector('.hello')
  .scrollIntoView({ behavior: 'smooth', padding: 20 });
```

**Comment by iamdustan** [comment]
Hey @davestewart,

This project is only meant to polyfill behavior that is in spec and not be a general purpose scrolling library. If that is added to the spec then we could definitely take it on.

**Comment by davestewart** [comment]
Hey, thanks for the reply!

In the meantime I wrote my own code for getting regions, adding padding, determining offset then `scrollBy(x, y)` using this lib.

Thank you!
