### ISSUE TITLE
Is this a polyfill or does it do extra stuff not in the spec?

### ISSUE THREAD

**Issue by callumlocke** [iamdustan/smoothscroll#19]
The MDN docs for [scroll()](https://developer.mozilla.org/en-US/docs/Web/API/Window/scroll) and [scrollBy()](https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollBy) don't mention the 'behavior' option, or the way of calling it with a single options argument (`{left, top, behavior}`) as in test.html.

Is this because the MDN docs are incomplete, or because smoothscroll implements extra features not in the spec?

Either way it would be good to give some usage examples in the readme.

**Comment by iamdustan** [comment]
It is intended to be a polyfill. You can see some of the relevant parts of the upcoming spec here:

https://drafts.csswg.org/cssom-view/#extensions-to-the-window-interface

**Comment by jeremenichelli** [comment]
According to draft's last version, it should @callumlocke 👌
