### ISSUE TITLE
el.scrollIntroView() doesn't work

### ISSUE THREAD

**Issue by ebidel** [iamdustan/smoothscroll#2]
I think this has something to do with the reuse of `window.scrollTo` in this method:
https://github.com/iamdustan/smoothscroll/blob/master/smoothscroll.js#L71

That will try to scroll to a specific location int the document, but it doesn't work for
elements with `overflow:scroll`...the primary use case for `el.scrollIntoView()`.
This is especially true if body has `overflow:hidden`. Nothing will happen.

**Comment by jeremenichelli** [comment]
@ebidel I know this issue is old, but in case you have time and since I don't know a lot about SHADOW DOM can you provide a simple fiddle to show when this doesn't work? I would like to solve this bug.

**Comment by ThiRaBrTNK** [comment]
I'm not sure if I fixed exact this bug in #18, but at least the same symptom.

**Comment by callumlocke** [comment]
Where it says "incomplete" in the readme, is that referring to this issue?

**Comment by stevenvachon** [comment]
This function only works correctly in Firefox -- meaning that it's probably using the native function. This polyfill is kinda useless.

**Comment by jeremenichelli** [comment]
Fixing this soon. Mayor refactor on the way 😃

**Comment by jeremenichelli** [comment]
Just merged a new version addressing some issues around `scrollIntoView` among other improvements so this polyfill is kinda useful to you now @stevenvachon, check it out and let us know if you find a specific bug.

**Comment by jeremenichelli** [comment]
All good people in this thread, if you use the `scrollIntoView` thing not working correctly, rise your hand or an issue better with an example and browser where it fails so I can help you. Happy smooth scrolling!

**Comment by stevenvachon** [comment]
Thanks!
