### ISSUE TITLE
request for an npm package

### ISSUE THREAD

**Issue by jiyinyiyong** [iamdustan/smoothscroll#23]
We need better solution of dependency management, please.

And the name https://www.npmjs.com/package/smoothscroll is already taken, maybe try another.

**Comment by jiyinyiyong** [comment]
Well https://www.npmjs.com/package/smoothscroll-polyfill

**Comment by jeremenichelli** [comment]
@jiyinyiyong is there any chance you can pass me the ownership to **smoothscroll-polyfill**? I'm planning on doing a refactor containing a _commonjs_ valid approach and some other fixes and was planning to use that name.

**Comment by jiyinyiyong** [comment]
@jeremenichelli sure. I found your name on npm. Check it out.

**Comment by jeremenichelli** [comment]
Thanks a lot @jiyinyiyong 🙏

**Comment by jeremenichelli** [comment]
This should now work correctly as an npm package requiring it and calling the `polyfill` method like this:
```js
require('smoothscroll-polyfill').polyfill();
```
