### ISSUE TITLE
scrollTo() removed

### ISSUE THREAD

**Issue by stevenvachon** [iamdustan/smoothscroll#26]
Should be included for completeness, and is also a breaking changes from v0.2.1

**Comment by jeremenichelli** [comment]
Hi @stevenvachon, in which browser this isn't working? I've tested in Chrome and I can use `window.scrollTo` with and without **smooth behavior**.

**Comment by stevenvachon** [comment]
Safari 9.1.1

**Comment by stevenvachon** [comment]
Closing this as my issue is caused by #27
