### ISSUE TITLE
off by 1px?

### ISSUE THREAD

**Issue by stevenvachon** [iamdustan/smoothscroll#30]
```js
document.getElementById("top").scrollIntoView({ behavior:"smooth" });
```
scrolls to 1px shy of the top of the page. The element is at the same y location as `<body>` and `<html>`.

The issue does not occur when not using smooth behaviour -- even in Safari, which does not have any native implementation of this function.

**Comment by jeremenichelli** [comment]
Just tested this in the demopage, last version of Safari and it works perfectly fine.

![scrollIntoView in Safari](https://cloud.githubusercontent.com/assets/3856481/15900843/51bf4798-2d77-11e6-83d5-89ad79ac663b.png)

After applying `scrollIntoView` the y scrolled position is `0`. Check if you have some margin on the `#top` element or padding in the body.

If you can please specify version of Safari and provide a gist with the example so I can reproduce exactly your issue. Thanks.

**Comment by stevenvachon** [comment]
I have `* { padding:0.025px }` as to un-collapse all margins. Darn. Wonder what can be done.

**Comment by jeremenichelli** [comment]
Well, the thing is that there's an easing function controlling the scrolling steps so rounding numbers might cause an undesired effect. It seems to me that this is project specific issue and not a problem with the polyfill.

**Comment by stevenvachon** [comment]
Ok, thanks.

**Comment by jeremenichelli** [comment]
No problem. As a final note, If you need to go to the initial position I would try to use `scroll` or `scrollTo` with `0` value for `top` though I don't know well the needs around your project.

**Comment by stevenvachon** [comment]
I'm using a simple `pushState` router for smooth-scrolling page fragments/hashes. I just did `html,body { padding-top:0 }` which was fine for my site design.
