### ISSUE TITLE
Element.prototype.scroll{To, By}?

### ISSUE THREAD

**Issue by SaschaNaz** [iamdustan/smoothscroll#32]
It seems that [the latest WD](http://www.w3.org/TR/2016/WD-cssom-view-1-20160317/#extension-to-the-element-interface) has scroll, scrollTo, scrollBy methods on Element interface. Will this polyfill support them?

``` webidl
partial interface Element {
  ...
  void scroll(optional ScrollToOptions options);
  void scroll(unrestricted double x, unrestricted double y);
  void scrollTo(optional ScrollToOptions options);
  void scrollTo(unrestricted double x, unrestricted double y);
  void scrollBy(optional ScrollToOptions options);
  void scrollBy(unrestricted double x, unrestricted double y);
  ...
};
```

**Comment by jeremenichelli** [comment]
You're right, they are part of the partial spec and are present in the current implementation in Firefox. Right now they are not present in the polyfill. It could be a nice future addition.

**Comment by jeremenichelli** [comment]
Confirming this was added a while ago, though there are some bugs and inconsistency that I'm going to tackle in the following days.
