### ISSUE TITLE
Add smoothscroll-polyfill to cdnjs?

### ISSUE THREAD

**Issue by simono** [iamdustan/smoothscroll#33]
It would be great if smoothscroll-polyfill would be available on [cdnjs](https://cdnjs.com/#q=smoothscroll-polyfill). What do you think?

Thanks for the great library :)

**Comment by jeremenichelli** [comment]
+1 to that

On Wednesday, 29 June 2016, Simon Olofsson <notifications@github.com> wrote:

> It would be great if smoothscroll-polyfill would be available on cdnjs
> <https://cdnjs.com/#q=smoothscroll-polyfill>. What do you think?
>
> Thanks for the great library :)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/iamdustan/smoothscroll/issues/33>, or mute the thread
> <https://github.com/notifications/unsubscribe/ADrYYQcLffED2s1MmrA8QNgM8UesJMlxks5qQk9kgaJpZM4JBAuy>
> .
>


-- 

*Jeremias Menichelli*


*web developer*
skype | jeremias.menichelli
<http://jeremenichelli.github.io>
github | jeremenichelli

**Comment by jeremenichelli** [comment]
I don't know what the steps are to make it available there, if you can shed some light on this it would be great. I can take care of it in the enxt weeks.

**Comment by simono** [comment]
@jeremenichelli Sounds great, thanks. I never submitted anything to cdnjs myself, so I can just link to the [official docs](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md). If I can help, just let me know.

**Comment by 7rulnik** [comment]
You can use https://npmcdn.com/smoothscroll

**Comment by simono** [comment]
@7rulnik The correct link is https://npmcdn.com/smoothscroll-polyfill@0.3.3 :)

**Comment by jeremenichelli** [comment]
Actually if you don't specify a version it will return the latest published version, so both links are correct. Closing this one. We can reopen it if someone feels this _must_ be in **cdnjs**.

**Comment by simono** [comment]
You're right about the version. But `smoothscroll` is a different package than `smoothscroll-polyfill` 😄

**Comment by jeremenichelli** [comment]
Oh totally, my bad @simono
