### ISSUE TITLE
Remove .polyfill() api.

### ISSUE THREAD

**Issue by DylanPiercey** [iamdustan/smoothscroll#35]
Forcing commonjs to use `smoothscroll.polyfill()` makes it a bit lame to use with es6 modules.

```js
import smoothscroll from 'smoothscroll-polyfill'
smoothscroll.polyfill()
```

vs

```js
import 'smoothscroll-polyfill'
```

Is there any benefit to forcing `.polyfill` to be called?

**Comment by DanielHeath** [comment]
It provides a hook for things like `rewire` and makes it easier to manage when doing e.g. universal server rendering.

**Comment by jeremenichelli** [comment]
@DylanPiercey this not an issue indeed but more of a decision to follow the pattern used in other polyfills. in this case, the best way is to provide to developer to implicitly apply the polyfill, as @DanielHeath mentioned, to avoid errors in certain cases.

**Comment by coladict** [comment]
I think this explanation should be added to the Readme.md
```
import smoothscroll from 'smoothscroll-polyfill';
smoothscroll.polyfill(); // call when initializing web-page or it won't work
```
Because as someone not familiar to the disaster that is the JS eco-system, I would never know that the given example `require('smoothscroll-polyfill').polyfill();` translates to that.
