### ISSUE TITLE
scrollIntoView X-Axis only manupulates Y-Axis too 

### ISSUE THREAD

**Issue by thisconnect** [iamdustan/smoothscroll#45]
Hi, first thanks for the polyfill!!

When using scrollIntoView on an element where the Y-Axis is already in the view but X-Axis is not, the Y-Axis seems to be manipulated too (see test case with polyfill).

Please test the 2 test cases by manually scrolling up and down. An interval is set to alternately call scrollIntoView on the nav anchors.

Expected: no effect on the Y-Axis. Scrolls the X-Axis of the nav element

Issue: "With the pollyfill" the Y-Aixs seems to be unnecessary modified. Manually scrolling the Y-Axis is hindered when scrollIntoView is called. (issue on chrome, no issue on firefox)

without polyfill
https://jsfiddle.net/tofu/245w4hxe/10/

with polyfill
https://jsfiddle.net/tofu/245w4hxe/12/

**Comment by jeremenichelli** [comment]
@thisconnect I think I solved this on last release so I'm closing it, if you can give a try and confirm that would be great. If you are still seeing an issue feel free to reopen. Thanks!
