### ISSUE TITLE
Smooth scrolling doesn't work on Chrome when defining specific elements

### ISSUE THREAD

**Issue by ahmadalfy** [iamdustan/smoothscroll#46]
The smooth behaviour doesn't work on Chrome even on the demo website when selecting elements to scroll to.

Google Chrome	56.0.2924.3 (Official Build) dev (64-bit)
Revision	66f73b3ae5a592d70e00602e87a783535ffe967e-refs/branch-heads/2924@{#54}

**How to reproduce**:

1. Visit http://iamdustan.com/smoothscroll/ using Chrome
2. Open devtools console
3. Run
```
document.querySelector('header').scrollIntoView({ behavior: 'smooth' });
```
or
```
document.querySelector('.hello').scrollIntoView({ behavior: 'smooth' });
```

**Expected result**: smooth scrolling.
**Actual result**: jump scrolling.

**Comment by iamdustan** [comment]
Is that Chrome Canary that you’re running? I just tested on Chrome 54 (stable build) and it is working as expected.

I’m guessing that this is a WIP feature in Chrome Canary.

What does the following evaluate to in your browser console?

```
('scrollBehavior' in document.documentElement.style)
```

**Comment by ahmadalfy** [comment]
No that's not Canary that's the dev channel. It is more stable than Canary. You can find more information about Chrome releases here: https://www.chromium.org/getting-involved/dev-channel

That statement evalutates to `true`.

**Comment by iamdustan** [comment]
yup. that’s the issue then. Either the dev channel has an incomplete implementation of scrollBehavior or the spec has changed and the polyfill is wrong. Regardless if that is evaluating to true then the polyfill assumes that the browser supports the spec and doesn’t hijack all the scroll* methods.

**Comment by ahmadalfy** [comment]
Awesome. Will close the issue and check future stable releases and report back. Thank you!

**Comment by iamdustan** [comment]
Rad. Thanks, @ahmadalfy!
