### ISSUE TITLE
Element scrollIntoView while accommodating for the height of a fixed header

### ISSUE THREAD

**Issue by themaxsandelin** [iamdustan/smoothscroll#47]
Just tried this out and the performance is perfect, but I lack the ability to scroll an element into view while accommodating for a fixed element like a header. Would be great to have an extra argument in for the scrollIntoView method that would let you push the element up or down.

**Comment by joshuatuscan** [comment]
I'd also love this, or some way of having a callback when animation is finished to be able to re-adjust the element.

**Comment by themaxsandelin** [comment]
On @joshuatuscan comment, I would absolutely love a callback for when the scroll movement is completely done. 👌🏻

**Comment by jeremenichelli** [comment]
People, remember this is a polyfill and not a library. Unless a callback is added to the spec is not likely to make it in the code.

The best option is to listen to the scroll event and check for the final `y` position to execute some call and later remove the listener until a new smooth scroll ocurrence.

**Comment by themaxsandelin** [comment]
It's a good suggestion but does not apply to any sort of website with fixed height content as this would break when tested on larger devices with smaller scrolling distance.

**Comment by oscarhandsome** [comment]
somebody know how to do? or need use offset and animation to move from top?

**Comment by jeremenichelli** [comment]
If there are some element floating that will imply the scorlling need to be readjust you need to manually get the y position of the elements and use `window.scroll` will the resulting metrics gathered.

**Comment by jeremenichelli** [comment]
Closing since the feature requested is not included in the official specs. If you find a use case that works on native implementations and not with the polyfill feel free to report it. Thanks!

**Comment by ctf0** [comment]
here is a solution

```js
let item = // what we want to scroll to
let wrapper = // the wrapper you will scroll inside
let count = item.offsetTop - wrapper.scrollTop - xx // xx = any extra distance from top ex. 60
wrapper.scrollBy({top: count, left: 0, behavior: 'smooth'})
```

**Comment by 13lackNinja** [comment]
In case anyone's still searching, I got around this issue with a fixed position header by setting the `{ block: 'end' }` for my element in element.scrollIntoView. 

This conveniently lines it up based on the bottom of the element rather than the top, and you can take care of the height of the element yourself by simply subtracting the height of your header or other fixed element.

**Comment by adamthedorsey** [comment]
This is an old thread but I just came across it while working out my own solution. Using `scroll()` instead of `scrollBy()` seems to make a lot more sense to me. 

I simply did...

```javascript
var offset = 50; // sticky nav height
var el = document.querySelector('.some-element'); // element you are scrolling to
window.scroll({ top: (el.offsetTop - offset), left: 0, behavior: 'smooth' });
```

**Comment by naeembashir** [comment]
That helped in my case —
<br>
HTML

    <div class='stick-to-top'></>

Javascript

    document.getElementsByClassName('stick-to-top')[0].scrollIntoView({behavior: "smooth", block: "center"});

CSS
    
    .stick-to-top {
     padding-bottom: 400px;
    }
