### ISSUE TITLE
Option to always use the polyfill instead of native implementation

### ISSUE THREAD

**Issue by feimosi** [iamdustan/smoothscroll#49]
I've come across a strange situation where Firefox's native `scrollIntoView` implementation behaves strange and unnatural, whereas the polyfill works perfectly. 
Thus I think there should be an option to always override this behaviour (for some special cases).

**Comment by jeremenichelli** [comment]
You're right about the `scrollIntoView` issue, the implementation has a bug and was already reported to Mozilla. This is actually a good idea to incorporate.

**Comment by JoshEllinger** [comment]
Yes please do this 👍  firefox is unusable with scrollIntoView without this

**Comment by crccheck** [comment]
I made a simple demo where Firefox's smooth scrolling doesn't work while regular scrolling does http://output.jsbin.com/wunofejamu

**Comment by jeremenichelli** [comment]
Feature added on v0.4.0, go to the README to find out how to force polyfill. Thanks for the contributions y'all!
