### ISSUE TITLE
Need to update focus for keyboard accessibility

### ISSUE THREAD

**Issue by tedw** [iamdustan/smoothscroll#50]
The polyfill should shift focus to the target element after scrolling. This allows keyboard users to continue tabbing without being sent back up to the original link location.

I’ve used the technique below in my own custom smooth scroll scripts and it’s worked great:
```js
// Setting 'tabindex' to -1 takes an element out of normal 
// tab flow but allows it to be focused via javascript
$el.attr('tabindex', -1).on('blur focusout', function() {

    // when focus leaves this element, 
    // remove the tabindex attribute
    $(this).removeAttr('tabindex');

}).focus(); // focus on the content container
```
Source: https://www.bignerdranch.com/blog/web-accessibility-skip-navigation-links/

Thanks for your work on this script! Looking forward to switching to it once this a11y issue is addressed (I would submit a PR but don’t have time right now, unfortunately).

**Comment by iamdustan** [comment]
Hey @tedw. Do you know if the spec and/or native implementation do this as well?

**Comment by tedw** [comment]
I didn’t see anything mentioned in the [spec](https://www.w3.org/TR/cssom-view-1/#smooth-scrolling), but this is the default behavior for jump links in all browsers, and is how Firefox implemented it.

Here’s a little demo I made to test it http://output.jsbin.com/nucilij/quiet

**Comment by iamdustan** [comment]
Hmm...when I press `[tab]` in Firefox (Developer Edition), focus only stays in the browser chrome (url bar, search bar, etc).

Am I missing something?

**Comment by tedw** [comment]
Oh, right, I actually had to look this up recently. For whatever reason, it’s really difficult to enable tabbing in Firefox on Macs. Here are the steps:

>1. In System Preferences>Keyboard, in the keyboard shortcuts pane, check the "all controls" radio.
>2. In Firefox, type "about:config" in the URL bar. There is no accessibility.tabfocus preference on the mac, so you'll have to make one. Right click in the window, create a new "integer" pref, and set it to 7.

From http://stackoverflow.com/a/11713537/673457

**Comment by Mottie** [comment]
@tedw, that code would destroy any pre-defined tabindex. It would be better to add any original tabindex into a data-attribute, then restore it.

**Comment by tedw** [comment]
@Mottie Good point!

**Comment by missmatsuko** [comment]
This issue was closed, but I didn't see any commits for it. Was the problem ever fixed?
