### ISSUE TITLE
scrollIntoView in fixed overlay div scrolls containing body each time too

### ISSUE THREAD

**Issue by kierenj** [iamdustan/smoothscroll#51]
I have a modal and I'm scrolling to tabbed sections with it.  Unfortunately no `scroll()` on container elements yet to do it manually, and `scrollIntoView()` scrolls the main window body in the background too.

**Comment by kierenj** [comment]
Nevermind, just found #44 ... I'll use that

**Comment by kierenj** [comment]
The PR doesn't fix the issue for me, still scrolls the body in the background as well as the modal.

**Comment by kierenj** [comment]
It's the `// reveal parent in viewport` part of `Element.prototype.scrollIntoView` that's the issue.  If in a `fixed` container, this shouldn't be executed I guess?
Would also love to ignore horizontal scrolling.
I think the best workaround for me is to have the per-element `scroll()`.  I'll see about putting together a PR..

**Comment by lunatolun** [comment]
I had a similar issue. Don't know why but somehow adding overflow: auto and height: 100%  to html/body fixed it for me..

```
html, body {
    overflow: auto;
    height: 100%
}
```
