### ISSUE TITLE
scroll into view does not work in chrome 55/56

### ISSUE THREAD

**Issue by matt3224** [iamdustan/smoothscroll#52]
Hi I have tested this in the stable branch of chrome in both versions using the demo page.

I assume it is because chrome doesn't have the full implementation so the polyfill thinks it is fully supported natively in the browser but it isn't as `smooth` isn't supported.

Hopefully someone else can confirm.

**Comment by tstock55** [comment]
Having the same issue as Matt

**Comment by jeremenichelli** [comment]
On Chrome 55 and it looks like it's working OK. At least on the polyfill's site. If you have an example where `scrollIntoView` fails please share it.

Is it Chrome _stable_ or _canary_?

**Comment by dalemartyn** [comment]
yeah its not working for me in chrome 57. `'scrollBehavior' in document.documentElement.style` is true. wondering if there's a different way to feature detect?

**Comment by dalemartyn** [comment]
just to clarify, i think chrome now supports `window.scroll({ behavior: 'smooth' })` natively, but doesn't support `element.scrollIntoView({ behavior: 'smooth' })`

**Comment by benvoynick** [comment]
Still working for me in Chrome 57.

I note that document.documentElement.style.scrollBehavior is undefined on my copy of Chrome.

**Comment by sk1p** [comment]
Interesting. Maybe a platform issue? 
On Linux using Chrome Version 58.0.3029.81 (64-bit):

 * Native smooth scrolling using `window.scroll`, `window.scrollBy` works
 * `scrollIntoView` ignores the smooth behavior
 * `"scrollBehavior" in document.documentElement.style` is `true`

On Android, Chrome 57:

 * `"scrollBehavior" in document.documentElement.style` is `false`
 * because of that, the polyfill is used successfully...

What platform are y'all on?

**Comment by sk1p** [comment]
I think I found the issue. Can you check if the flag "Experimental Web Platform features" is enabled in chrome://flags? In my tests, enabling this flag leads to `"scrollBehavior" in document.documentElement.style === true` and the erratic behavior.

**Comment by sk1p** [comment]
For reference, the [bug](https://bugs.chromium.org/p/chromium/issues/detail?id=648446) and [code review](https://codereview.chromium.org/2650343008/) for the implementation of smooth scrolling with `scrollIntoView` in Chrome

**Comment by dalemartyn** [comment]
yeah, you're right. i had the flag enabled. my bad.

**Comment by jeremenichelli** [comment]
Closing the issue since in Chrome stable with no experimental flag being enabled the style check the polyfills does returns `false`.
