### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by elado** [iamdustan/smoothscroll#59]
The version on npm is not the latest code, can you please release an up-to-date version?

**Comment by mattecapu** [comment]
+1

**Comment by jeremenichelli** [comment]
@iamdustan probably we forgot to do `npm publish`, do you want to merge the PRs and publish? If not I can publish the latest tomorrow or Tuesday.

**Comment by iamdustan** [comment]
I’m going to work on getting #39 in this week and then will get a new version published.

**Comment by jeremenichelli** [comment]
Thanks pal!

**Comment by steida** [comment]
@iamdustan Please.

**Comment by iamdustan** [comment]
Looks like latest master is already published as 0.3.5.
