### ISSUE TITLE
Endless timer

### ISSUE THREAD

**Issue by elado** [iamdustan/smoothscroll#60]
Using this code:

```js
scroller.scrollBy({ left: 300, behavior: 'smooth' })
```

and getting into this state of an endless interval/raf:

![scrollerror](https://cloud.githubusercontent.com/assets/51488/24933782/fe9d2290-1ecc-11e7-823c-5a2680cf5104.gif)

**Comment by iamdustan** [comment]
Thanks for the gif in the report, @elado!

Would you be able to try applying the diff from #58 to see if that fixes this for you?

**Comment by besuhoff** [comment]
@iamdustan that's a really nice fix that almost does the thing but consider the following case:
```js
element.scrollBy({ left: -10, behavior: 'smooth' })
```

In that specific case, `context.y` and `currentY` are both `NaN` so `currentY !== context.y` is always true

**Comment by jeremenichelli** [comment]
@besuhoff we think this situation was covered in past releases, I'll close the issue, but feel free to download the last version and reopen this one if it keeps happening. Thanks!
