### ISSUE TITLE
Minified version

### ISSUE THREAD

**Issue by nextgenthemes** [iamdustan/smoothscroll#61]
please

**Comment by arlyon** [comment]
This is extremely easy to do yourself. https://jscompress.com/

**Comment by jeremenichelli** [comment]
We are gonna make this a priority and explore different compress strategies to see which works better for the library.

**Comment by nextgenthemes** [comment]
@arlyon I know how to compress js. But I would like this to be installed and updated with npm and just load the files form the dist folder. Like most people do with any other npm module. Its pretty standard for npm modules to have compressed files distributed as well.

@jeremenichelli not much experience js compression with this but I would just follow https://github.com/twbs/bootstrap/blob/v4-dev/package.json and drop gulp and use what they use because its well maintained. They use eslint as well. This file is so small I think it does not really matter much.

**Comment by arlyon** [comment]
If you are planning on releasing a pre-minified version you should consider uploading to cdnjs or another content delivery as well.

**Comment by pschfr** [comment]
FYI it is on cdnjs - https://cdnjs.com/libraries/iamdustan-smoothscroll

**Comment by jeremenichelli** [comment]
Minified version addded on v0.4.0
