### ISSUE TITLE
Why 468?

### ISSUE THREAD

**Issue by agudulin** [iamdustan/smoothscroll#65]
Hi,

I have a quick question about this `SCROLL_TIME`: https://github.com/iamdustan/smoothscroll/blob/master/src/smoothscroll.js#L22

I just wonder how did you get this number 😸

**Comment by iamdustan** [comment]
tbh it's pretty arbitrary. Ideally we would calculate the total scroll diff to make ahead of time and have the SCROLL_TIME be dynamic based upon that.

**Comment by agudulin** [comment]
@iamdustan if I got it right, to get `SCROLL_TIME` based on scroll distance we need a function `(element.getBoundingClientRect().top, window.innerHeight, someConstant) => SCROLL_TIME` then.

In this case the `someConstant` value would be a magic number as well :)

**Comment by iamdustan** [comment]
Yeah, that sounds right to me at first glance. It still won’t be a perfect representation of the host platform behavior, but it’ll be closer than what it currently is.

**Comment by jeremenichelli** [comment]
Yeap, we actually have an issue for that https://github.com/iamdustan/smoothscroll/issues/13

**Comment by thaingnguyen** [comment]
What do you guys think about extending the API to let the callsite overrides the duration if needed?

**Comment by jeremenichelli** [comment]
@thaingnguyen thanks for the suggestion, I will explore a global constant the polyfill can pick up.
