### ISSUE TITLE
Scroll with mouse stops working after first call to `scrollBy` with `behavior: 'smooth'` param

### ISSUE THREAD

**Issue by Pavek** [iamdustan/smoothscroll#66]
Unfortunately, I don't have isolated test-case, but issue is constantly/easily reproduced [here][1] (scroll down to News & Media ) with Chrome 58/Win.

Note: this is about _horizontal_ scrolling of a div with `overflow-x: scroll` style.

The test case is (to run from DevTools on the page above, one command a time):
```
document.querySelector('.news-feed').scrollBy({ left: 2000 }); //OK
document.querySelector('.news-feed').scrollLeft = 0; // OK
```
After that everything is still fine - scroll is back to 0.

```
document.querySelector('.news-feed').scrollBy({ left: 2000, behavior: 'smooth' }); // OK
document.querySelector('.news-feed').scrollLeft = 0; // Fail and scroll is broken!
```
=> After that scroll is broken: neither `scrollLeft` is back to 0, nor *scrolling with mouse* is possible. Which is a deal-breaker.

[1]: https://karambasec-stage.herokuapp.com/

**Comment by rasmusfl0e** [comment]
I ran into the same bug; it looks like supplying both `top` and `left` is currently needed to make it work.

Omitting either throws a `NaN` in the works and and the loop never exits because `NaN !== undefined` :D

**Comment by rasmusfl0e** [comment]
@iamdustan Oops - I just realized that this specific issue relates to `scrollBy` and not `scroll`/`scrollTo` (which is what my PR fixed). It's the same bug though - the fix just needs to be applied to `scrollBy` also :D

**Comment by iamdustan** [comment]
@rasmusfl0e yeah, is that what #63 was doing? Too bad I gave it conflicts landing yours first :innocent:
