### ISSUE TITLE
Scrolling with an offset?

### ISSUE THREAD

**Issue by joemottershaw** [iamdustan/smoothscroll#67]
I'm aware that this is a polyfil and not a library so it doesn't add any additional features or parameters, so I know I'm kinda of contradicting myself by asking... but I was wondering if there has been any discussion of the possibility of adding an offset to the `scrollIntoView()` method? Or if anyone knows if this is something that vendors will be adding to the core functionality to all scroll methods in the future?

I know there's obviously numerous ways you can get this working, for example getting the elements `y` position and applying the offset to it and using `scrollTo();` instead, but it would be nice if it's possible to scroll the element into view with say 20px offset before the element with `scrollIntoView()`, like so:

`document.querySelector('.hello').scrollIntoView({ top: -=20, behavior: 'smooth' });`

Using the `-=` to just modify the already gotten `y` value of `top` and adding/subtracting the offset value. Not requesting it as a feature or anything, just looking for some extra input or alternative ideas to see what people think :)

**Comment by jeremenichelli** [comment]
From what I'm seeing I don't imagine that something like this will be added to the spec. The easiest solution is to get the element's offset, and scroll its parent to that offset `- 20`, I'm not seeing it as something hard to accomplish.

**Comment by joemottershaw** [comment]
Thought that might be the case, the method you said is how I've been doing it and you're right, it's not hard to implement, but I thought I'd ask either way just in case I was missing something or if it had already been discussed.

**Comment by jeremenichelli** [comment]
Makes sense. This is a great place to discuss this kind of things, and don't hesitate on doing it again.
