### ISSUE TITLE
Link to demo from Readme.md incorrect?

### ISSUE THREAD

**Issue by joemcloE** [iamdustan/smoothscroll#77]
I'm not sure which is correct, I suspect the later, but there seems to be two demo sites floating around:
http://iamdustan.com/smoothscroll/
and
https://ghybs.github.io/smoothscroll/
The second page includes `element.scroll` and `element.scrollTo` methods which are not featured in the first demo page but do seem to work with the latest npm release

Thanks
Joe

**Comment by jeremenichelli** [comment]
Hi Joe. The second one must be some fork of the repository, I imagine someone added `element.scroll` and updated the site correctly in that version. The link on the README is correct by the way.
