### ISSUE TITLE
Make compatible with ES6 imports

### ISSUE THREAD

**Issue by drexkdal** [iamdustan/smoothscroll#79]
Please use `exports.default` instead of setting `module.exports` to avoid this error when importing with ES6 Modules syntax:

```
export 'default' (imported as 'smoothscroll') was not found in 'smoothscroll-polyfill'
```

**Comment by drexkdal** [comment]
I'm no longer sure that this is a problem with the way `exports` is used. May be something with Babel/Webpack instead. Mystified....

**Comment by jeremenichelli** [comment]
I think the issue is you might be using Webpack 2.x or 3.x and you are using babel-preset-es2015 but haven't set `modules` option to `false`. Babel modules transpiling might be in conflict with Webpack parsing which already suports module notation out od the box.

**Comment by drexkdal** [comment]
I am setting `modules: false`, but I've found the solution:

I didn't realize that it was normal practice to exclude `node_modules` from Babel compilation. Now that I've set the `include` (or, alternatively, `exclude`) property in my Babel config, things are working as expected.
