### ISSUE TITLE
Scrolling only to the half of the target element in Chrome

### ISSUE THREAD

**Issue by dakur** [iamdustan/smoothscroll#93]
I have easy script which smooth scrolls a view when clicking an anchor and am using this polyfill.
```js
import SmoothScroll from 'smoothscroll-polyfill';

document.querySelector('#test').scrollIntoView({
	behavior: 'smooth'
});
```
```html
<div id="test">...</div>
...
<a href="#test">scroll to #test</div>
```

Now, it suddenly started to scroll only to the half of the element I'm targetting to (`#test`). But I'm pretty sure it worked well in Chrome when I was writing it (~July 2017).  
As of version 62, Chrome [has native support](https://caniuse.com/#feat=scrollintoview) for `behavior: smooth` property passing to `scrollIntoView()` method. I have a suspiction that the strange behaviour is related to the new Chrome version. If I open it in Chromium 46, it works well. Firefox works well as well.

Illustration:
![smoothscroll-bug](https://user-images.githubusercontent.com/9862581/32836653-d7b3e83c-ca0a-11e7-8e5f-b958da3b82a4.png)

**Comment by dakur** [comment]
P.S.: I am using `"smoothscroll-polyfill": "^0.4.0"`.

**Comment by jeremenichelli** [comment]
I think this is due to Chrome implementation.

If you want to test the polyfill's behavior you can force it by doing:

```js
import smoothScroll from 'smoothscroll-polyfill';

window.__forceSmoothScrollPolyfill__ = true;
smoothScroll.polyfill();
```

That way you will be able to see if the problem is on Chrome's side or on this polyfill. That's why on Chrome 46 it works _well_, because there's no native implementation and the polyfill comes in.

_Note that Chrome implements the spec different from Firefox and centers the element on scrollIntoView instead of pushing its position to the top of the viewport._

**Comment by dakur** [comment]
If I run:
```js
import smoothScroll from 'smoothscroll-polyfill';

window.__forceSmoothScrollPolyfill__ = true;
smoothScroll.polyfill();

document.addEventListener('DOMContentLoaded', () => {
	document.querySelector('#test').scrollIntoView({
		behavior: 'smooth'
	});
});
```

It still behave the same, thus I guess it's polyfill's bug.

**Comment by jeremenichelli** [comment]
Looks like, can you provided and isolated test case, like in a gist or jsfiddle I can debug? That would make reproduction easier for me to see if it's actually a problem with the polyfill.

**Comment by dakur** [comment]
@jeremenichelli Ok, I'm sorry, it's Chrome's fault. Probably build failed somehow when I was testing it so the `force` has not applied. Now, I see it works with `window.__forceSmoothScrollPolyfill__ = true;`.

**Comment by jeremenichelli** [comment]
Great man, thanks for updating the issue!
