### ISSUE TITLE
Polyfill fails in Safari 11

### ISSUE THREAD

**Issue by laika-repo** [iamdustan/smoothscroll#94]
Safari 11 supports CommonJS modules but not scrollBehavior so the following check seems to break the Polyfill in Safari 11

if (typeof exports === 'object')

**Comment by jeremenichelli** [comment]
Good catch, I'll add an additional check to `module` object so it works there.

I will try to add it today since it's a deal breaker.

**Comment by jeremenichelli** [comment]
@laika-repo can you confirm the version of Safari you are using and how you are using the polyfill (direct script addition or bundling).

I'm on Safari 11.0.1, `("object" == typeof exports)` returns `false` and the polyfill seems to be working. A reduced test would be ideal, but if not any additional information like errors in console are welcome.

**Comment by laika-repo** [comment]
@jeremenichelli Sorry, seems I was a bit too fast with my conclusions. In the context of our application it returns true but after further digging it turns out that's because we use Webpack.

**Comment by jeremenichelli** [comment]
Ok @laika-repo, how are you using the polyfill. If you are importing and bundling it you should do:

```js
import smoothscroll from 'smoothscroll-polyfill';

smoothscroll.polyfill();
```

So that the scripts takes effect. Let me know if this works for you so we can close this issue.

**Comment by laika-repo** [comment]
@jeremenichelli, that's the way we're doing it now and that works. So, as far as we're concerned this issue can be closed. Thanks for the quick response.

**Comment by jeremenichelli** [comment]
No problem, glad it's working.

**Comment by maddy2894** [comment]
I am using the following code to use smooth scroll
`const smoothscroll = require('smoothscroll-polyfill');

smoothscroll.polyfill();`
But still, scrollIntoView({behavior: 'smooth'}) doesn't work in IOS safari 12. It works in android chrome browser. Any additional code should I include?
