### ISSUE TITLE
weird scrolling issue

### ISSUE THREAD

**Issue by ctf0** [iamdustan/smoothscroll#96]
```js
let file = // the item i will scroll to
let wrapper = // a scrollable container
let count = file.offsetTop - wrapper.scrollTop - 20 // 20 is some offset from top

wrapper.scrollBy({top: count, left: 0, behavior: 'smooth'})
```

atm it works perfectly until the point where i resize the window for less than **1023px**, for some unknown reason the scroll doesnt work anymore & `wrapper.scrollTop == 0`.

the strange thing that using `file.scrollIntoView(false)` works at all situations minus the scroll animation.

so is there a way to fix that, or at least know the reason behind that behavior ?

**Comment by jeremenichelli** [comment]
Doesn't `file.scrollIntoView({ behavior: 'smooth' })` work?

If it doesn't, I would check what happens on a browser with native support of the spec and see if it behaves different from the polyfill. If not I might need a reduced test case to verify what's going on.

**Comment by ctf0** [comment]
`file.scrollIntoView({ behavior: 'smooth' })` will scroll to `top: 0` of body which is not ideal.
and as the polyfill doesn't support any options other than scrolling to the bottom of the item then i have to stick to `scrollBy`

about the browsers, sadly each one have its own idea of the specs, so FF sometimes it works and sometimes it not, Chrome doesnt support the behavior option in anyway or shape, Safari / IE "die already"

**Comment by jeremenichelli** [comment]
So weird, would love an example on that inconsistency. I'm pretty sure that this can be solved with a combination of a couple of scroll functions, but hard to infer from the description.

**Comment by ctf0** [comment]
unfortunately atm the only way to test this is within a package am working on https://github.com/ctf0/Laravel-Media-Manager 😢 , however is there something in particular i could do on my end that may help you ?

**Comment by jeremenichelli** [comment]
I will try to get a better understanding of the use case and see if I can recreate it. As far as we got, I got the feeling this is not a problem of the polyfill indeed, but probably a complicated combination of scroll reposition steps. More taking in count that Firefox which is the best implementation of the spec yet is giving you inconsitent results.

**Comment by ctf0** [comment]
i actually had to enabel `window.__forceSmoothScrollPolyfill__ = true` to make sure that the behavior is the same "bad or good" across the browsers

**Comment by ctf0** [comment]
**update**

disabled the polyfill, and instead used `file.scrollIntoView({behavior: 'smooth', block: 'end', inline: 'end'})` 

which works correctly all around except safari "no surprise".

again not sure what exactly is the reason behind this but for now, its seems its working.
