### ISSUE TITLE
is it loaded twice?

### ISSUE THREAD

**Issue by Marinolinderhof** [iamdustan/smoothscroll#98]
I made a function that looks for a element and scrolls to that element i use thi polyfill. But i can't figure out if it is loaded twice when called twice.

```
import smoothScroll from 'smoothscroll-polyfill';
smoothScroll.polyfill();

// oversimplified component
const smoothScrollTo = (el) => {
  const element = document.querySelector(el);

  element && element.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
}
```

This is code example of my code. If i look in the source i see:
```
  if ('scrollBehavior' in d.documentElement.style
    && w.__forceSmoothScrollPolyfill__ !== true) {
    return;
  }
```
but can't figure out if you set `scrollBehavior` in the `document.documentElement.style` so i assume smoothScroll polyfill is added everytime you run the code smoothScroll.polyfill();

is that true? 

Thanks for the reply much appreciated and thanks again for this amazing polyfill!

**Comment by jeremenichelli** [comment]
Hi @Marinolinderhof, every time you call the `polyfill`method the code _runs_, it loads once. You only need to executed one time like you're doing  in your example.

The condition block described by you checks if the `scrollBehavior` CSS property exists in the current browser which we use to bail out in case the spec is already supported so we don't override the implementation.

Hope my explanations helped :)
